id: 04c_backend_registry_autoload
title: "Auto-register backends; graceful fallback; list capabilities"
priority: 62
deps: [ "04_vectordb_backends" ]
steps:
  - name: "Add auto-registration"
    run: |
      applypatch codex/patches/04c_registry_autoload.patch
  - name: "CLI list and snapshot"
    run: |
      python -m ragcore.cli list > eval/fixtures/goldens/backends_capabilities.json
  - name: "Unit tests"
    run: |
      pytest tests/unit/test_registry_autoload.py -q
success_criteria:
  - "missing C++ module doesn't crash; dummy present; list shows capabilities"
