id: 07c_transforms_sandbox_minimal_python
title: Transform sandbox (Python-only, network-off)
description: >
  Execute small Python transforms with time/memory limits; capture stdout/stderr; no shell yet.
acceptance:
  - tests/unit/test_transform_python_sandbox.py pass
steps:
  - Implement Sandbox.run_python(); configure resource limits; redact outputs in logs over size cap.
