id: 12_rest_facade
title: REST Parity Facade
description: >
  Thin FastAPI app that mirrors key MCP tools: /v1/search, /v1/plan, /v1/research,
  and HITL endpoints. Uses same service layer as MCP server.
goals:
  - Endpoints return same normalized schemas as MCP tool outputs.
  - JSON Envelope optional; prefer native normalized objects for /v1/*
steps:
  - Create apps/rest/main.py with FastAPI routes.
  - Wire routes to internal services that MCP uses.
  - Add OpenAPI tags and examples; mount healthcheck /health.
tests:
  - file: tests/e2e/test_rest_parity.py
    purpose: For a fixture request, REST and MCP return schema-equivalent results.
  - file: tests/unit/test_rest_openapi_sanity.py
    purpose: OpenAPI doc renders; required schemas present.
docs:
  - docs/rest_facade.md
