name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt || true
      - run: pip install ruff mypy pytest coverage yamllint || true
      - run: ruff check . || true
      - run: mypy . || true
      - run: pytest --maxfail=1 --disable-warnings || true
