name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python runtime with pip caching
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pybind11 || true
          pip install ruff mypy pytest coverage yamllint || true

      # Export pybind11_DIR (so CMake can find it)
      - name: Export pybind11_DIR
        run: |
          echo "pybind11_DIR=$(python -m pybind11 --cmakedir)" >> $GITHUB_ENV
          echo "Using pybind11_DIR=$pybind11_DIR"

      # Enable ccache to cache compiled C++ objects
      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          max-size: 500M

      # Configure CMake (only if CMakeLists.txt exists)
      - name: Configure CMake
        if: ${{ hashFiles('**/CMakeLists.txt') != '' }}
        env:
          pybind11_DIR: ${{ env.pybind11_DIR }}
        run: |
          cmake -S ./cpp -B build \
            -G Ninja \
            -Dpybind11_DIR="$pybind11_DIR" \
            -DPYBIND11_FINDPYTHON=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      # Build project (native CMake/Ninja)
      - name: Build
        if: ${{ hashFiles('**/CMakeLists.txt') != '' }}
        run: cmake --build build -- -j"$(nproc)"

      # Run lint / type checks / tests (non-fatal like your original)
      - name: Ruff
        run: ruff check . || true

      - name: MyPy
        run: mypy . || true

      - name: PyTest
        run: pytest --maxfail=1 --disable-warnings || true
