name: ci
"on":
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python runtime for lint/type/test steps
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install deps (now benefited by cache)
      - run: pip install -r requirements.txt || true

      # Tools (these will also hit the pip cache)
      - run: pip install ruff mypy pytest coverage yamllint || true

      - run: ruff check . || true
      - run: mypy . || true
      - run: pytest --maxfail=1 --disable-warnings || true
